name = "GADM"
uuid = "a8dd9ffe-31dc-4cf5-a379-ea69100a8233"
authors = ["Aayush Joglekar <aayushjog@gmail.com> and contributors"]
version = "0.4.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArchGDAL = "0.9"
DataDeps = "0.7"
GeoInterface = "1"
Tables = "1.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
